language: node_js


# https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  - osx


node_js:
  - "7"
  - "6"


cache:
  yarn: true


before_script:
  - yarn global add gulp-cli


script: gulp build


# notifications:
#   email:
#     - john.doe@example.com
